# Generated by Django 3.0.8 on 2020-07-22 15:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(default=datetime.datetime(2020, 7, 22, 15, 35, 33, 408522))),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IP', 'In progress'), ('CT', 'Completed'), ('HD', 'Hold')], default='NEW', max_length=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 7, 22, 15, 35, 33, 409599))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.Task')),
            ],
        ),
    ]
